{$DEFINE APPVCL}
program AREppVcl;

uses
  Vcl.Forms,
  DataSet.Serialize,
  System.SysUtils,
  System.IOUtils,
  uMain.Vcl.View in 'uMain.Vcl.View.pas' {MainVclView},
  uLogin.View in 'Shared\View\uLogin.View.pas' {LoginView},
  uHlp in '..\REST\Shared\Util\uHlp.pas',
  uEnv.Vcl in 'Config\uEnv.Vcl.pas',
  uApplicationError.View in 'Shared\View\uApplicationError.View.pas' {ApplicationErrorView},
  uHandle.Exception in 'Shared\View\uHandle.Exception.pas',
  uNotificationView in 'Shared\View\uNotificationView.pas' {NotificationView},
  uBase.Index.View in 'Shared\View\uBase.Index.View.pas' {BaseIndexView},
  uBrand.Service in 'Module\Stock\Brand\Service\uBrand.Service.pas',
  uReq in 'Config\uReq.pas',
  uUserLogged in 'Config\uUserLogged.pas',
  uAclUser in 'Module\Auth\AclUser\Entity\uAclUser.pas',
  uBase.Entity in 'Shared\Entity\uBase.Entity.pas',
  uIndexResult in 'Config\uIndexResult.pas',
  uMemTable.Factory in 'Config\uMemTable.Factory.pas',
  uAppVcl.Types in 'Config\uAppVcl.Types.pas',
  uBrand.ViewModel in 'Module\Stock\Brand\ViewModel\uBrand.ViewModel.pas',
  uBrand.ViewModel.Interfaces in 'Module\Stock\Brand\ViewModel\uBrand.ViewModel.Interfaces.pas',
  uBase.ViewModel.Interfaces in 'Shared\ViewModel\uBase.ViewModel.Interfaces.pas',
  uAlert.View in 'Shared\View\uAlert.View.pas' {AlertView},
  uYesOrNo.View in 'Shared\View\uYesOrNo.View.pas' {YesOrNoView},
  uDTM in 'Config\uDTM.pas' {DTM: TDataModule},
  uBase.Input.View in 'Shared\View\uBase.Input.View.pas' {BaseInputView},
  uBase.Service in 'Shared\Service\uBase.Service.pas',
  uBrand.Index.View in 'Module\Stock\Brand\View\uBrand.Index.View.pas' {BrandIndexView},
  uBrand.Input.View in 'Module\Stock\Brand\View\uBrand.Input.View.pas' {BrandInputView},
  uBrand.Service.Interfaces in 'Module\Stock\Brand\Service\uBrand.Service.Interfaces.pas',
  uBase.DTO in '..\REST\Shared\DTO\uBase.DTO.pas',
  uBase.Filter.DTO in '..\REST\Shared\DTO\uBase.Filter.DTO.pas',
  uBrand.Filter.DTO in '..\REST\Module\Stock\Brand\DTO\uBrand.Filter.DTO.pas',
  uBrand.Input.DTO in '..\REST\Module\Stock\Brand\DTO\uBrand.Input.DTO.pas',
  uBrand.Show.DTO in '..\REST\Module\Stock\Brand\DTO\uBrand.Show.DTO.pas',
  uTrans in '..\REST\Shared\Resources\uTrans.pas',
  uTrans.Sale in '..\REST\Shared\Resources\uTrans.Sale.pas',
  uTrans.Types in '..\REST\Shared\Resources\uTrans.Types.pas',
  uCity.Index.View in 'Module\General\City\View\uCity.Index.View.pas' {CityIndexView},
  uCity.Input.View in 'Module\General\City\View\uCity.Input.View.pas' {CityInputView},
  uCity.Filter.DTO in '..\REST\Module\General\City\DTO\uCity.Filter.DTO.pas',
  uCity.Input.DTO in '..\REST\Module\General\City\DTO\uCity.Input.DTO.pas',
  uCity.Show.DTO in '..\REST\Module\General\City\DTO\uCity.Show.DTO.pas',
  uCity.ViewModel.Interfaces in 'Module\General\City\ViewModel\uCity.ViewModel.Interfaces.pas',
  uCity.ViewModel in 'Module\General\City\ViewModel\uCity.ViewModel.pas',
  uCity.Service.Interfaces in 'Module\General\City\Service\uCity.Service.Interfaces.pas',
  uCity.Service in 'Module\General\City\Service\uCity.Service.pas',
  uPerson.Index.View in 'Module\General\Person\View\uPerson.Index.View.pas' {PersonIndexView},
  uPerson.ViewModel in 'Module\General\Person\ViewModel\uPerson.ViewModel.pas',
  uPerson.Input.View in 'Module\General\Person\View\uPerson.Input.View.pas' {PersonInputView},
  uPerson.ViewModel.Interfaces in 'Module\General\Person\ViewModel\uPerson.ViewModel.Interfaces.pas',
  uPerson.Service in 'Module\General\Person\Service\uPerson.Service.pas',
  uPerson.Service.Interfaces in 'Module\General\Person\Service\uPerson.Service.Interfaces.pas',
  uPerson.Filter.DTO in '..\REST\Module\General\Person\DTO\uPerson.Filter.DTO.pas',
  uPerson.Input.DTO in '..\REST\Module\General\Person\DTO\uPerson.Input.DTO.pas',
  uPerson.Show.DTO in '..\REST\Module\General\Person\DTO\uPerson.Show.DTO.pas',
  uPersonContact.Input.DTO in '..\REST\Module\General\Person\DTO\uPersonContact.Input.DTO.pas',
  uPersonContact.Show.DTO in '..\REST\Module\General\Person\DTO\uPersonContact.Show.DTO.pas',
  uPerson.Types in '..\REST\Module\General\Person\Domain\Types\uPerson.Types.pas',
  uPersonContacts.ViewModel in 'Module\General\Person\ViewModel\uPersonContacts.ViewModel.pas',
  uPersonContact.Input.View in 'Module\General\Person\View\uPersonContact.Input.View.pas' {PersonContactInputView},
  uSearchLegalEntityNumber.Lib in 'Shared\Lib\uSearchLegalEntityNumber.Lib.pas',
  uSearchZipCode.Lib in 'Shared\Lib\uSearchZipCode.Lib.pas',
  uAclRole in 'Module\Auth\AclRole\Entity\uAclRole.pas',
  uAclRole.Types in '..\REST\Module\Auth\AclRole\Domain\Types\uAclRole.Types.pas',
  uCategory.Index.View in 'Module\Stock\Category\View\uCategory.Index.View.pas' {CategoryIndexView},
  uCategory.Input.View in 'Module\Stock\Category\View\uCategory.Input.View.pas' {CategoryInputView},
  uCategory.ViewModel.Interfaces in 'Module\Stock\Category\ViewModel\uCategory.ViewModel.Interfaces.pas',
  uCategory.ViewModel in 'Module\Stock\Category\ViewModel\uCategory.ViewModel.pas',
  uCategory.Service in 'Module\Stock\Category\Service\uCategory.Service.pas',
  uCategory.Service.Interfaces in 'Module\Stock\Category\Service\uCategory.Service.Interfaces.pas',
  uCategory.Filter.DTO in '..\REST\Module\Stock\Category\DTO\uCategory.Filter.DTO.pas',
  uCategory.Input.DTO in '..\REST\Module\Stock\Category\DTO\uCategory.Input.DTO.pas',
  uCategory.Show.DTO in '..\REST\Module\Stock\Category\DTO\uCategory.Show.DTO.pas',
  uNcm.Index.View in 'Module\Stock\Ncm\View\uNcm.Index.View.pas' {NcmIndexView},
  uNcm.Input.View in 'Module\Stock\Ncm\View\uNcm.Input.View.pas' {NcmInputView},
  uNcm.ViewModel.Interfaces in 'Module\Stock\Ncm\ViewModel\uNcm.ViewModel.Interfaces.pas',
  uNcm.ViewModel in 'Module\Stock\Ncm\ViewModel\uNcm.ViewModel.pas',
  uNcm.Service.Interfaces in 'Module\Stock\Ncm\Service\uNcm.Service.Interfaces.pas',
  uNcm.Service in 'Module\Stock\Ncm\Service\uNcm.Service.pas',
  uNcm.Filter.DTO in '..\REST\Module\Stock\Ncm\DTO\uNcm.Filter.DTO.pas',
  uNcm.Input.DTO in '..\REST\Module\Stock\Ncm\DTO\uNcm.Input.DTO.pas',
  uNcm.Show.DTO in '..\REST\Module\Stock\Ncm\DTO\uNcm.Show.DTO.pas',
  uSize.ViewModel.Interfaces in 'Module\Stock\Size\ViewModel\uSize.ViewModel.Interfaces.pas',
  uSize.ViewModel in 'Module\Stock\Size\ViewModel\uSize.ViewModel.pas',
  uSize.Index.View in 'Module\Stock\Size\View\uSize.Index.View.pas' {SizeIndexView},
  uSize.Input.View in 'Module\Stock\Size\View\uSize.Input.View.pas' {SizeInputView},
  uSize.Service in 'Module\Stock\Size\Service\uSize.Service.pas',
  uSize.Service.Interfaces in 'Module\Stock\Size\Service\uSize.Service.Interfaces.pas',
  uSize.Filter.DTO in '..\REST\Module\Stock\Size\DTO\uSize.Filter.DTO.pas',
  uSize.Input.DTO in '..\REST\Module\Stock\Size\DTO\uSize.Input.DTO.pas',
  uSize.Show.DTO in '..\REST\Module\Stock\Size\DTO\uSize.Show.DTO.pas',
  uStorageLocation.Index.View in 'Module\Stock\StorageLocation\View\uStorageLocation.Index.View.pas' {StorageLocationIndexView},
  uStorageLocation.Input.View in 'Module\Stock\StorageLocation\View\uStorageLocation.Input.View.pas' {StorageLocationInputView},
  uStorageLocation.ViewModel.Interfaces in 'Module\Stock\StorageLocation\ViewModel\uStorageLocation.ViewModel.Interfaces.pas',
  uStorageLocation.ViewModel in 'Module\Stock\StorageLocation\ViewModel\uStorageLocation.ViewModel.pas',
  uStorageLocation.Service.Interfaces in 'Module\Stock\StorageLocation\Service\uStorageLocation.Service.Interfaces.pas',
  uStorageLocation.Service in 'Module\Stock\StorageLocation\Service\uStorageLocation.Service.pas',
  uStorageLocation.Filter.DTO in '..\REST\Module\Stock\StorageLocation\DTO\uStorageLocation.Filter.DTO.pas',
  uStorageLocation.Input.DTO in '..\REST\Module\Stock\StorageLocation\DTO\uStorageLocation.Input.DTO.pas',
  uStorageLocation.Show.DTO in '..\REST\Module\Stock\StorageLocation\DTO\uStorageLocation.Show.DTO.pas',
  uUnit.Input.View in 'Module\Stock\Unit\View\uUnit.Input.View.pas' {UnitInputView},
  uUnit.Index.View in 'Module\Stock\Unit\View\uUnit.Index.View.pas' {UnitIndexView},
  uUnit.ViewModel in 'Module\Stock\Unit\ViewModel\uUnit.ViewModel.pas',
  uUnit.ViewModel.Interfaces in 'Module\Stock\Unit\ViewModel\uUnit.ViewModel.Interfaces.pas',
  uUnit.Service in 'Module\Stock\Unit\Service\uUnit.Service.pas',
  uUnit.Service.Interfaces in 'Module\Stock\Unit\Service\uUnit.Service.Interfaces.pas',
  uUnit.Filter.DTO in '..\REST\Module\Stock\Unit\DTO\uUnit.Filter.DTO.pas',
  uUnit.Input.DTO in '..\REST\Module\Stock\Unit\DTO\uUnit.Input.DTO.pas',
  uUnit.Show.DTO in '..\REST\Module\Stock\Unit\DTO\uUnit.Show.DTO.pas',
  uProduct.Input.View in 'Module\Stock\Product\View\uProduct.Input.View.pas' {ProductInputView},
  uProduct.Index.View in 'Module\Stock\Product\View\uProduct.Index.View.pas' {ProductIndexView},
  uProduct.ViewModel.Interfaces in 'Module\Stock\Product\ViewModel\uProduct.ViewModel.Interfaces.pas',
  uProduct.ViewModel in 'Module\Stock\Product\ViewModel\uProduct.ViewModel.pas',
  uProduct.Service.Interfaces in 'Module\Stock\Product\Service\uProduct.Service.Interfaces.pas',
  uProduct.Service in 'Module\Stock\Product\Service\uProduct.Service.pas',
  uProduct.Filter.DTO in '..\REST\Module\Stock\Product\DTO\uProduct.Filter.DTO.pas',
  uProduct.Input.DTO in '..\REST\Module\Stock\Product\DTO\uProduct.Input.DTO.pas',
  uProduct.Show.DTO in '..\REST\Module\Stock\Product\DTO\uProduct.Show.DTO.pas',
  uProduct.Types in '..\REST\Module\Stock\Product\Domain\Types\uProduct.Types.pas',
  uCompany.Input.View in 'Module\General\Company\View\uCompany.Input.View.pas' {CompanyInputView},
  uCompany.Index.View in 'Module\General\Company\View\uCompany.Index.View.pas' {CompanyIndexView},
  uCompany.ViewModel in 'Module\General\Company\ViewModel\uCompany.ViewModel.pas',
  uCompany.ViewModel.Interfaces in 'Module\General\Company\ViewModel\uCompany.ViewModel.Interfaces.pas',
  uCompany.Service in 'Module\General\Company\Service\uCompany.Service.pas',
  uCompany.Service.Interfaces in 'Module\General\Company\Service\uCompany.Service.Interfaces.pas',
  uCompany.Filter.DTO in '..\REST\Module\General\Company\DTO\uCompany.Filter.DTO.pas',
  uCompany.Input.DTO in '..\REST\Module\General\Company\DTO\uCompany.Input.DTO.pas',
  uCompany.Show.DTO in '..\REST\Module\General\Company\DTO\uCompany.Show.DTO.pas',
  uConsumption.Index.View in 'Module\General\Consumption\View\uConsumption.Index.View.pas' {ConsumptionIndexView},
  uConsumption.Input.View in 'Module\General\Consumption\View\uConsumption.Input.View.pas' {ConsumptionInputView},
  uConsumption.ViewModel in 'Module\General\Consumption\ViewModel\uConsumption.ViewModel.pas',
  uConsumption.ViewModel.Interfaces in 'Module\General\Consumption\ViewModel\uConsumption.ViewModel.Interfaces.pas',
  uConsumption.Service in 'Module\General\Consumption\Service\uConsumption.Service.pas',
  uConsumption.Service.Interfaces in 'Module\General\Consumption\Service\uConsumption.Service.Interfaces.pas',
  uConsumption.Filter.DTO in '..\REST\Module\General\Consumption\DTO\uConsumption.Filter.DTO.pas',
  uConsumption.Input.DTO in '..\REST\Module\General\Consumption\DTO\uConsumption.Input.DTO.pas',
  uConsumption.Show.DTO in '..\REST\Module\General\Consumption\DTO\uConsumption.Show.DTO.pas',
  uStation.Index.View in 'Module\General\Station\View\uStation.Index.View.pas' {StationIndexView},
  uStation.Input.View in 'Module\General\Station\View\uStation.Input.View.pas' {StationInputView},
  uStation.ViewModel in 'Module\General\Station\ViewModel\uStation.ViewModel.pas',
  uStation.ViewModel.Interfaces in 'Module\General\Station\ViewModel\uStation.ViewModel.Interfaces.pas',
  uStation.Service.Interfaces in 'Module\General\Station\Service\uStation.Service.Interfaces.pas',
  uStation.Service in 'Module\General\Station\Service\uStation.Service.pas',
  uStation.Filter.DTO in '..\REST\Module\General\Station\DTO\uStation.Filter.DTO.pas',
  uStation.Input.DTO in '..\REST\Module\General\Station\DTO\uStation.Input.DTO.pas',
  uStation.Show.DTO in '..\REST\Module\General\Station\DTO\uStation.Show.DTO.pas',
  uBank.Input.View in 'Module\Financial\Bank\View\uBank.Input.View.pas' {BankInputView},
  uBank.Index.View in 'Module\Financial\Bank\View\uBank.Index.View.pas' {BankIndexView},
  uBank.ViewModel in 'Module\Financial\Bank\ViewModel\uBank.ViewModel.pas',
  uBank.ViewModel.Interfaces in 'Module\Financial\Bank\ViewModel\uBank.ViewModel.Interfaces.pas',
  uBank.Service in 'Module\Financial\Bank\Service\uBank.Service.pas',
  uBank.Service.Interfaces in 'Module\Financial\Bank\Service\uBank.Service.Interfaces.pas',
  uBank.Filter.DTO in '..\REST\Module\Financial\Bank\DTO\uBank.Filter.DTO.pas',
  uBank.Input.DTO in '..\REST\Module\Financial\Bank\DTO\uBank.Input.DTO.pas',
  uBank.Show.DTO in '..\REST\Module\Financial\Bank\DTO\uBank.Show.DTO.pas',
  uBankAccount.Input.View in 'Module\Financial\BankAccount\View\uBankAccount.Input.View.pas' {BankAccountInputView},
  uBankAccount.Index.View in 'Module\Financial\BankAccount\View\uBankAccount.Index.View.pas' {BankAccountIndexView},
  uBankAccount.ViewModel.Interfaces in 'Module\Financial\BankAccount\ViewModel\uBankAccount.ViewModel.Interfaces.pas',
  uBankAccount.ViewModel in 'Module\Financial\BankAccount\ViewModel\uBankAccount.ViewModel.pas',
  uBankAccount.Service.Interfaces in 'Module\Financial\BankAccount\Service\uBankAccount.Service.Interfaces.pas',
  uBankAccount.Service in 'Module\Financial\BankAccount\Service\uBankAccount.Service.pas',
  uBankAccount.Filter.DTO in '..\REST\Module\Financial\BankAccount\DTO\uBankAccount.Filter.DTO.pas',
  uBankAccount.Input.DTO in '..\REST\Module\Financial\BankAccount\DTO\uBankAccount.Input.DTO.pas',
  uBankAccount.Show.DTO in '..\REST\Module\Financial\BankAccount\DTO\uBankAccount.Show.DTO.pas',
  uChartOfAccount.ViewModel.Interfaces in 'Module\Financial\ChartOfAccount\ViewModel\uChartOfAccount.ViewModel.Interfaces.pas',
  uChartOfAccount.ViewModel in 'Module\Financial\ChartOfAccount\ViewModel\uChartOfAccount.ViewModel.pas',
  uChartOfAccount.Index.View in 'Module\Financial\ChartOfAccount\View\uChartOfAccount.Index.View.pas' {ChartOfAccountIndexView},
  uChartOfAccount.Input.View in 'Module\Financial\ChartOfAccount\View\uChartOfAccount.Input.View.pas' {ChartOfAccountInputView},
  uChartOfAccount.Service in 'Module\Financial\ChartOfAccount\Service\uChartOfAccount.Service.pas',
  uChartOfAccount.Service.Interfaces in 'Module\Financial\ChartOfAccount\Service\uChartOfAccount.Service.Interfaces.pas',
  uChartOfAccount.Filter.DTO in '..\REST\Module\Financial\ChartOfAccount\DTO\uChartOfAccount.Filter.DTO.pas',
  uChartOfAccount.Input.DTO in '..\REST\Module\Financial\ChartOfAccount\DTO\uChartOfAccount.Input.DTO.pas',
  uChartOfAccount.Show.DTO in '..\REST\Module\Financial\ChartOfAccount\DTO\uChartOfAccount.Show.DTO.pas',
  uCostCenter.Input.View in 'Module\Financial\CostCenter\View\uCostCenter.Input.View.pas' {CostCenterInputView},
  uCostCenter.Index.View in 'Module\Financial\CostCenter\View\uCostCenter.Index.View.pas' {CostCenterIndexView},
  uCostCenter.ViewModel in 'Module\Financial\CostCenter\ViewModel\uCostCenter.ViewModel.pas',
  uCostCenter.ViewModel.Interfaces in 'Module\Financial\CostCenter\ViewModel\uCostCenter.ViewModel.Interfaces.pas',
  uCostCenter.Service.Interfaces in 'Module\Financial\CostCenter\Service\uCostCenter.Service.Interfaces.pas',
  uCostCenter.Service in 'Module\Financial\CostCenter\Service\uCostCenter.Service.pas',
  uCostCenter.Filter.DTO in '..\REST\Module\Financial\CostCenter\DTO\uCostCenter.Filter.DTO.pas',
  uCostCenter.Input.DTO in '..\REST\Module\Financial\CostCenter\DTO\uCostCenter.Input.DTO.pas',
  uCostCenter.Show.DTO in '..\REST\Module\Financial\CostCenter\DTO\uCostCenter.Show.DTO.pas',
  uPaymentTerm.Input.View in 'Module\Financial\Payment\View\uPaymentTerm.Input.View.pas' {PaymentTermInputView},
  uPayment.Index.View in 'Module\Financial\Payment\View\uPayment.Index.View.pas' {PaymentIndexView},
  uPayment.Input.View in 'Module\Financial\Payment\View\uPayment.Input.View.pas' {PaymentInputView},
  uPaymentTerms.ViewModel in 'Module\Financial\Payment\ViewModel\uPaymentTerms.ViewModel.pas',
  uPayment.ViewModel in 'Module\Financial\Payment\ViewModel\uPayment.ViewModel.pas',
  uPayment.ViewModel.Interfaces in 'Module\Financial\Payment\ViewModel\uPayment.ViewModel.Interfaces.pas',
  uPayment.Service in 'Module\Financial\Payment\Service\uPayment.Service.pas',
  uPayment.Service.Interfaces in 'Module\Financial\Payment\Service\uPayment.Service.Interfaces.pas',
  uPayment.Filter.DTO in '..\REST\Module\Financial\Payment\DTO\uPayment.Filter.DTO.pas',
  uPayment.Input.DTO in '..\REST\Module\Financial\Payment\DTO\uPayment.Input.DTO.pas',
  uPayment.Show.DTO in '..\REST\Module\Financial\Payment\DTO\uPayment.Show.DTO.pas',
  uPaymentTerm.Input.DTO in '..\REST\Module\Financial\Payment\DTO\uPaymentTerm.Input.DTO.pas',
  uPaymentTerm.Show.DTO in '..\REST\Module\Financial\Payment\DTO\uPaymentTerm.Show.DTO.pas',
  uCashFlow.Input.View in 'Module\Financial\CashFlow\View\uCashFlow.Input.View.pas' {CashFlowInputView},
  uCashFlowTransaction.Input.View in 'Module\Financial\CashFlow\View\uCashFlowTransaction.Input.View.pas' {CashFlowTransactionInputView},
  uCashFlow.Index.View in 'Module\Financial\CashFlow\View\uCashFlow.Index.View.pas' {CashFlowIndexView},
  uCashFlowTransactions.ViewModel in 'Module\Financial\CashFlow\ViewModel\uCashFlowTransactions.ViewModel.pas',
  uCashFlow.ViewModel in 'Module\Financial\CashFlow\ViewModel\uCashFlow.ViewModel.pas',
  uCashFlow.ViewModel.Interfaces in 'Module\Financial\CashFlow\ViewModel\uCashFlow.ViewModel.Interfaces.pas',
  uCashFlow.Service.Interfaces in 'Module\Financial\CashFlow\Service\uCashFlow.Service.Interfaces.pas',
  uCashFlow.Service in 'Module\Financial\CashFlow\Service\uCashFlow.Service.pas',
  uCashFlow.Filter.DTO in '..\REST\Module\Financial\CashFlow\DTO\uCashFlow.Filter.DTO.pas',
  uCashFlow.Input.DTO in '..\REST\Module\Financial\CashFlow\DTO\uCashFlow.Input.DTO.pas',
  uCashFlow.Show.DTO in '..\REST\Module\Financial\CashFlow\DTO\uCashFlow.Show.DTO.pas',
  uCashFlowTransaction.Input.DTO in '..\REST\Module\Financial\CashFlow\DTO\uCashFlowTransaction.Input.DTO.pas',
  uCashFlowTransaction.Show.DTO in '..\REST\Module\Financial\CashFlow\DTO\uCashFlowTransaction.Show.DTO.pas',
  uCashFlowTransaction.Types in '..\REST\Module\Financial\CashFlow\Domain\Types\uCashFlowTransaction.Types.pas',
  uBillPayReceive.Input.View in 'Module\Financial\BillPayReceive\View\uBillPayReceive.Input.View.pas' {BillPayReceiveInputView},
  uBillPayReceive.Index.View in 'Module\Financial\BillPayReceive\View\uBillPayReceive.Index.View.pas' {BillPayReceiveIndexView},
  uBillPayReceive.ViewModel in 'Module\Financial\BillPayReceive\ViewModel\uBillPayReceive.ViewModel.pas',
  uBillPayReceive.ViewModel.Interfaces in 'Module\Financial\BillPayReceive\ViewModel\uBillPayReceive.ViewModel.Interfaces.pas',
  uBillPayReceive.Service.Interfaces in 'Module\Financial\BillPayReceive\Service\uBillPayReceive.Service.Interfaces.pas',
  uBillPayReceive.Service in 'Module\Financial\BillPayReceive\Service\uBillPayReceive.Service.pas',
  uBillPayReceive.Filter.DTO in '..\REST\Module\Financial\BillPayReceive\DTO\uBillPayReceive.Filter.DTO.pas',
  uBillPayReceive.Input.DTO in '..\REST\Module\Financial\BillPayReceive\DTO\uBillPayReceive.Input.DTO.pas',
  uBillPayReceive.Show.DTO in '..\REST\Module\Financial\BillPayReceive\DTO\uBillPayReceive.Show.DTO.pas',
  uBillPayReceive.Types in '..\REST\Module\Financial\BillPayReceive\Domain\Types\uBillPayReceive.Types.pas',
  uSale.Index.View in 'Module\Business\Sale\View\uSale.Index.View.pas' {SaleIndexView},
  uSaleItems.ViewModel in 'Module\Business\Sale\ViewModel\uSaleItems.ViewModel.pas',
  uSale.ViewModel in 'Module\Business\Sale\ViewModel\uSale.ViewModel.pas',
  uSale.ViewModel.Interfaces in 'Module\Business\Sale\ViewModel\uSale.ViewModel.Interfaces.pas',
  uSaleItem.Input.View in 'Module\Business\Sale\View\uSaleItem.Input.View.pas' {SaleItemInputView},
  uSale.Input.View in 'Module\Business\Sale\View\uSale.Input.View.pas' {SaleInputView},
  uSale.Service in 'Module\Business\Sale\Service\uSale.Service.pas',
  uSale.Service.Interfaces in 'Module\Business\Sale\Service\uSale.Service.Interfaces.pas',
  uSale.Filter.DTO in '..\REST\Module\Business\Sale\DTO\uSale.Filter.DTO.pas',
  uSale.Input.DTO in '..\REST\Module\Business\Sale\DTO\uSale.Input.DTO.pas',
  uSale.Show.DTO in '..\REST\Module\Business\Sale\DTO\uSale.Show.DTO.pas',
  uSaleItem.Input.DTO in '..\REST\Module\Business\Sale\DTO\uSaleItem.Input.DTO.pas',
  uSaleItem.Show.DTO in '..\REST\Module\Business\Sale\DTO\uSaleItem.Show.DTO.pas',
  uSalePayment.Input.DTO in '..\REST\Module\Business\Sale\DTO\uSalePayment.Input.DTO.pas',
  uSalePayment.Show.DTO in '..\REST\Module\Business\Sale\DTO\uSalePayment.Show.DTO.pas',
  uSale.Types in '..\REST\Module\Business\Sale\Domain\Types\uSale.Types.pas',
  uSalePayments.ViewModel in 'Module\Business\Sale\ViewModel\uSalePayments.ViewModel.pas',
  uPaymentTerm.Locate.View in 'Module\Financial\Payment\View\uPaymentTerm.Locate.View.pas' {PaymentTermLocateView},
  uSalePayment.Input.View in 'Module\Business\Sale\View\uSalePayment.Input.View.pas' {SalePaymentInputView};

{$R *.res}

procedure ClearTempFolder;
begin
  // Caminho da pasta temporária
  const LTempPath = ExtractFilePath(ParamStr(0)) + TEMP_FOLDER;

  // Apagar diretório com todos os arquivos se existir
  if TDirectory.Exists(LTempPath) then
    TDirectory.Delete(LTempPath, True);

  // Criar diretório vazio
  ForceDirectories(LTempPath);
end;

begin
  // Limpar pasta temporária
  ClearTempFolder;

  // Configuração DataSetSerialize
  // O que está comentado é porque até o momento não foi necessário.
  // Cuidado ao mudar essas configurações.
  TDataSetSerializeConfig.GetInstance.CaseNameDefinition := TCaseNameDefinition.cndLower;
  //TDataSetSerializeConfig.GetInstance.DateTimeIsISO8601     := False;
  //TDataSetSerializeConfig.GetInstance.Export.FormatDateTime := 'yyyy-mm-dd"T"hh":"mm":"ss.000';
  //TDataSetSerializeConfig.GetInstance.Export.FormatDate     := 'yyyy-mm-dd';

  ReportMemoryLeaksOnShutdown := DebugHook <> 0;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDTM, DTM);
  Application.CreateForm(TMainVclView, MainVclView);
  Application.CreateForm(TNotificationView, NotificationView);
  Application.Run;
end.
